package com.fizz.pluginguard;

import java.io.File;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;

/**
 * Renders a self-contained, dark-themed HTML security report from a batch of {@link ScanResult}s and
 * writes it to disk. No external assets, no PDF library, no clock access — the timestamp is supplied by
 * the caller so the output is fully deterministic.
 */
final class ReportExporter {

    private ReportExporter() {
    }

    /**
     * Builds the full HTML document. Results are rendered INFECTED first, then UNVERIFIED, then TRUSTED.
     * All dynamic text is HTML-escaped. A {@code null} {@code results} list is treated as empty.
     *
     * @param serverName  display name of the guarded server
     * @param generatedAt caller-supplied timestamp string (this method never reads the clock)
     * @param vaultSize   number of trusted baselines in the vault
     * @param serverRoot  server root used to compute artifact paths via {@link Vault#rel(File, File)}
     * @param results     scan outcomes (may be {@code null})
     * @return a complete, standalone HTML document
     */
    static String html(String serverName, String generatedAt, int vaultSize, File serverRoot,
                        List<ScanResult> results) {
        List<ScanResult> rows = (results == null) ? new ArrayList<>() : new ArrayList<>(results);
        rows.sort(Comparator.comparingInt(r -> order(r.verdict())));

        int infected = 0;
        int unverified = 0;
        int trusted = 0;
        for (ScanResult r : rows) {
            switch (r.verdict()) {
                case INFECTED -> infected++;
                case UNVERIFIED -> unverified++;
                case TRUSTED -> trusted++;
            }
        }

        StringBuilder sb = new StringBuilder(4096 + rows.size() * 256);
        sb.append("<!DOCTYPE html>\n");
        sb.append("<html lang=\"en\">\n<head>\n");
        sb.append("<meta charset=\"UTF-8\">\n");
        sb.append("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
        sb.append("<title>PluginGuard Security Report — ").append(escape(serverName)).append("</title>\n");
        sb.append(styleBlock());
        sb.append("</head>\n<body>\n");
        sb.append("<div class=\"wrap\">\n");

        // Header
        sb.append("<header class=\"hdr\">\n");
        sb.append("<div class=\"brand\"><span class=\"shield\">&#9763;</span> PluginGuard"
                + " <span class=\"sub\">Security Report</span></div>\n");
        sb.append("<div class=\"meta\">\n");
        sb.append("<div class=\"meta-row\"><span class=\"meta-k\">Server</span>"
                + "<span class=\"meta-v\">").append(escape(serverName)).append("</span></div>\n");
        sb.append("<div class=\"meta-row\"><span class=\"meta-k\">Generated</span>"
                + "<span class=\"meta-v\">").append(escape(generatedAt)).append("</span></div>\n");
        sb.append("</div>\n");
        sb.append("</header>\n");

        // Summary stat row
        sb.append("<section class=\"stats\">\n");
        sb.append(stat("Scanned", Integer.toString(rows.size()), "neutral"));
        sb.append(stat("Infected", Integer.toString(infected), "infected"));
        sb.append(stat("Unverified", Integer.toString(unverified), "unverified"));
        sb.append(stat("Trusted", Integer.toString(trusted), "trusted"));
        sb.append(stat("Vault", Integer.toString(vaultSize), "neutral"));
        sb.append("</section>\n");

        // Results table
        sb.append("<section class=\"panel\">\n");
        sb.append("<table>\n<thead>\n<tr>");
        sb.append("<th class=\"c-verdict\">Verdict</th>");
        sb.append("<th class=\"c-artifact\">Artifact</th>");
        sb.append("<th class=\"c-hash\">SHA-256</th>");
        sb.append("<th class=\"c-reasons\">Reasons</th>");
        sb.append("</tr>\n</thead>\n<tbody>\n");

        if (rows.isEmpty()) {
            sb.append("<tr><td class=\"empty\" colspan=\"4\">No artifacts scanned.</td></tr>\n");
        } else {
            for (ScanResult r : rows) {
                sb.append(row(serverRoot, r));
            }
        }

        sb.append("</tbody>\n</table>\n");
        sb.append("</section>\n");

        // Footer
        sb.append("<footer class=\"ftr\">Generated by Guardio</footer>\n");
        sb.append("</div>\n</body>\n</html>\n");
        return sb.toString();
    }

    /**
     * Writes {@code html} to {@code dest} as UTF-8, creating parent directories as needed.
     *
     * @return {@code dest}
     * @throws IOException if the file cannot be written
     */
    static File write(File dest, String html) throws IOException {
        if (dest == null) {
            throw new IOException("destination is null");
        }
        File parent = dest.getParentFile();
        if (parent != null) {
            parent.mkdirs();
        }
        Files.write(dest.toPath(), html.getBytes(StandardCharsets.UTF_8));
        return dest;
    }

    /** Sort key: INFECTED (0) before UNVERIFIED (1) before TRUSTED (2). */
    private static int order(ScanResult.Verdict v) {
        return switch (v) {
            case INFECTED -> 0;
            case UNVERIFIED -> 1;
            case TRUSTED -> 2;
        };
    }

    /** Renders one summary stat card. {@code tone} selects the accent class. */
    private static String stat(String label, String value, String tone) {
        return "<div class=\"stat " + tone + "\">"
                + "<div class=\"stat-n\">" + escape(value) + "</div>"
                + "<div class=\"stat-l\">" + escape(label) + "</div>"
                + "</div>\n";
    }

    /** Renders one results table row for {@code r}. */
    private static String row(File serverRoot, ScanResult r) {
        ScanResult.Verdict v = r.verdict();
        String tone = switch (v) {
            case INFECTED -> "infected";
            case UNVERIFIED -> "unverified";
            case TRUSTED -> "trusted";
        };

        String artifact;
        File jar = r.jar();
        if (jar == null) {
            artifact = "(unknown)";
        } else if (serverRoot == null) {
            artifact = jar.getName();
        } else {
            artifact = Vault.rel(serverRoot, jar);
        }

        String sha = shortHash(r.sha256());

        List<String> reasons = r.reasons();
        String reasonText;
        if (reasons == null || reasons.isEmpty()) {
            reasonText = "—";
        } else {
            reasonText = String.join("; ", reasons);
        }

        StringBuilder sb = new StringBuilder(256);
        sb.append("<tr>");
        sb.append("<td class=\"c-verdict\"><span class=\"badge ").append(tone).append("\">")
                .append(escape(v.name())).append("</span></td>");
        sb.append("<td class=\"c-artifact\">").append(escape(artifact)).append("</td>");
        sb.append("<td class=\"c-hash mono\">").append(escape(sha)).append("</td>");
        sb.append("<td class=\"c-reasons\">").append(escape(reasonText)).append("</td>");
        sb.append("</tr>\n");
        return sb.toString();
    }

    /** First 16 chars of the hash plus an ellipsis; tolerant of null/short values. */
    private static String shortHash(String sha256) {
        if (sha256 == null || sha256.isEmpty()) {
            return "—";
        }
        if (sha256.length() <= 16) {
            return sha256;
        }
        return sha256.substring(0, 16) + "…";
    }

    /** Replaces the five markup-significant characters with HTML entities. Null is rendered as empty. */
    private static String escape(String s) {
        if (s == null || s.isEmpty()) {
            return "";
        }
        StringBuilder sb = new StringBuilder(s.length() + 16);
        for (int i = 0; i < s.length(); i++) {
            char c = s.charAt(i);
            switch (c) {
                case '&' -> sb.append("&amp;");
                case '<' -> sb.append("&lt;");
                case '>' -> sb.append("&gt;");
                case '"' -> sb.append("&quot;");
                case '\'' -> sb.append("&#39;");
                default -> sb.append(c);
            }
        }
        return sb.toString();
    }

    /** The single inline stylesheet for the whole document. */
    private static String styleBlock() {
        return "<style>\n"
                + ":root{--bg:#0b0e14;--panel:#11151f;--panel2:#0e1219;--line:#1e2532;"
                + "--txt:#e6e9ef;--muted:#8b93a7;--accent:#5b8cff;"
                + "--red:#ff5d6c;--red-bg:rgba(255,93,108,.12);"
                + "--amber:#ffb547;--amber-bg:rgba(255,181,71,.12);"
                + "--green:#3ddc84;--green-bg:rgba(61,220,132,.12);}\n"
                + "*{box-sizing:border-box;}\n"
                + "body{margin:0;background:var(--bg);color:var(--txt);"
                + "font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Helvetica,Arial,sans-serif;"
                + "font-size:14px;line-height:1.5;-webkit-font-smoothing:antialiased;}\n"
                + ".mono{font-family:'SF Mono',ui-monospace,'Cascadia Code',Consolas,'Liberation Mono',monospace;}\n"
                + ".wrap{max-width:980px;margin:0 auto;padding:40px 28px 64px;}\n"
                + ".hdr{display:flex;flex-wrap:wrap;justify-content:space-between;align-items:flex-end;"
                + "gap:20px;padding-bottom:22px;border-bottom:1px solid var(--line);}\n"
                + ".brand{font-size:24px;font-weight:700;letter-spacing:-.01em;}\n"
                + ".brand .shield{color:var(--accent);margin-right:6px;}\n"
                + ".brand .sub{font-size:13px;font-weight:500;color:var(--muted);"
                + "margin-left:8px;letter-spacing:.04em;text-transform:uppercase;}\n"
                + ".meta{text-align:right;font-size:13px;}\n"
                + ".meta-row{display:flex;gap:12px;justify-content:flex-end;}\n"
                + ".meta-k{color:var(--muted);min-width:72px;text-align:right;}\n"
                + ".meta-v{color:var(--txt);font-weight:500;}\n"
                + ".stats{display:grid;grid-template-columns:repeat(5,1fr);gap:12px;margin:26px 0;}\n"
                + ".stat{background:var(--panel);border:1px solid var(--line);border-radius:12px;"
                + "padding:16px 14px;text-align:center;position:relative;overflow:hidden;}\n"
                + ".stat::before{content:'';position:absolute;left:0;top:0;bottom:0;width:3px;"
                + "background:var(--muted);}\n"
                + ".stat.infected::before{background:var(--red);}\n"
                + ".stat.unverified::before{background:var(--amber);}\n"
                + ".stat.trusted::before{background:var(--green);}\n"
                + ".stat-n{font-size:28px;font-weight:700;letter-spacing:-.02em;}\n"
                + ".stat.infected .stat-n{color:var(--red);}\n"
                + ".stat.unverified .stat-n{color:var(--amber);}\n"
                + ".stat.trusted .stat-n{color:var(--green);}\n"
                + ".stat-l{font-size:11px;color:var(--muted);text-transform:uppercase;"
                + "letter-spacing:.08em;margin-top:4px;}\n"
                + ".panel{background:var(--panel);border:1px solid var(--line);border-radius:12px;"
                + "overflow:hidden;}\n"
                + "table{width:100%;border-collapse:collapse;}\n"
                + "thead th{background:var(--panel2);text-align:left;font-size:11px;font-weight:600;"
                + "color:var(--muted);text-transform:uppercase;letter-spacing:.07em;"
                + "padding:12px 16px;border-bottom:1px solid var(--line);}\n"
                + "tbody td{padding:13px 16px;border-bottom:1px solid var(--line);vertical-align:top;"
                + "word-break:break-word;}\n"
                + "tbody tr:last-child td{border-bottom:none;}\n"
                + "tbody tr:hover{background:rgba(255,255,255,.02);}\n"
                + ".c-verdict{width:120px;white-space:nowrap;}\n"
                + ".c-hash{width:170px;}\n"
                + ".c-artifact{color:var(--txt);}\n"
                + ".c-reasons{color:var(--muted);}\n"
                + ".empty{text-align:center;color:var(--muted);padding:28px 16px;}\n"
                + ".badge{display:inline-block;font-size:11px;font-weight:700;letter-spacing:.05em;"
                + "padding:4px 10px;border-radius:999px;border:1px solid transparent;}\n"
                + ".badge.infected{color:var(--red);background:var(--red-bg);border-color:var(--red);}\n"
                + ".badge.unverified{color:var(--amber);background:var(--amber-bg);border-color:var(--amber);}\n"
                + ".badge.trusted{color:var(--green);background:var(--green-bg);border-color:var(--green);}\n"
                + ".ftr{margin-top:28px;text-align:center;font-size:12px;color:var(--muted);"
                + "letter-spacing:.03em;}\n"
                + "@media(max-width:720px){.stats{grid-template-columns:repeat(2,1fr);}"
                + ".hdr{align-items:flex-start;}.meta,.meta-row{text-align:left;justify-content:flex-start;}}\n"
                + "</style>\n";
    }
}
